baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'rou.blue.theme'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
